services:
  - type: web
    plan: free
    name: django_base
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn django_base.asgi:application -k uvicorn.workers.UvicornWorker --workers 4 --timeout 60"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
